name: NaturalGrowth
main: thephilosophicat.tv.twitch.NatruralGrowth.NaturalGrowthMain
version: 1.0
api-version: '1.20'

commands:
   doPlaceDespawn:
      description: changes config to enable/dissable placing despawn items
      usage: "/<command> [True | False]" 
      permission: plugin.Rules
   do2x2Placement:
      description: changes config to enable/dissable placing items in a 2x2 fashion
      usage: "/<command> [True | False]" 
      permission: plugin.Rules

Permissions:
  plugin.Rules:
    description: allows players to change config settings
    default: op